version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      npm:
        patterns: ["*"]
        applies-to: version-updates
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly
    groups:
      actions:
        patterns: ["*"]
        applies-to: version-updates
    commit-message:
      prefix: deps
