version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
        versions: ["<1.0.0"]
    groups:
      npm:
        patterns: ["*"]
        applies-to: version-updates
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
        applies-to: version-updates
    commit-message:
      prefix: deps
