name: Coverage

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        runtime: [node, bun, deno]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        if: matrix.runtime == 'node'
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: 22.22

      - name: Setup Bun
        if: matrix.runtime == 'bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.9

      - name: Setup Deno
        if: matrix.runtime == 'deno'
        uses: denoland/setup-deno@v2

      - name: Install dependencies (node)
        if: matrix.runtime == 'node'
        run: npm ci

      - name: Install dependencies (bun)
        if: matrix.runtime == 'bun'
        run: bun install

      # - name: Install dependencies (deno)
      #   if: matrix.runtime == 'deno'
      #   # maybe?
      #   run: deno install

      - name: Run tests (node)
        if: matrix.runtime == 'node'
        run: npm test

      - name: Run tests (bun)
        if: matrix.runtime == 'bun'
        run: bun run test

      - name: Run tests (deno)
        if: matrix.runtime == 'deno'
        run: deno run -A npm:vitest run

      # don't for now
      # - name: Upload results to Codecov
      #   uses: codecov/codecov-action@v5
