name: Deprecate version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version(s)
        required: true

      message:
        type: string
        description: Deprecation message
        required: false
        default: "This version is no longer supported"

jobs:
  deprecate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Deprecate version
        run: npm deprecate "discolink@${{ inputs.version }}" "${{ inputs.message }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
