name: Publish release

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Bump version
        # TODO: remove allow-same-version after initial release
        run: npm version ${{ github.event.release.tag_name }} --git-tag-version false --allow-same-version

      - name: Install dependencies
        run: npm install

      - name: Build release
        run: npm run build

      - name: Commit release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add package.json

          git commit -m "chore(Release): v${{ github.event.release.tag_name }}"
          git push

      - name: Publish release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
