name: Publish release

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'execaman'
    permissions:
      contents: write
      id-token: write
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Bump version
        run: npm version ${{ github.event.release.tag_name }} --allow-same-version --git-tag-version false

      - name: Install dependencies
        run: npm install

      - name: Build release
        run: npm run build

      - name: Commit release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add package.json

          if git status --porcelain | grep -q .; then
            git commit -m "chore(Release): v${{ github.event.release.tag_name }}"
            git push origin HEAD:main
          else
            echo "Nothing to commit"
          fi

      - name: Publish release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
