name: Publication

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
      created: ${{ steps.release.outputs.release_created }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

  publish:
    needs: release
    if: ${{ needs.release.outputs.created }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          cache: npm
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Update npm
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build v${{ needs.release.outputs.version }}
        run: npm run build

      - name: Publish v${{ needs.release.outputs.version }}
        run: npm publish
